#! Spring Jackson
---
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

#! Spring Cache
---
spring:
  cache:
    cache-names: listAttributes, listCollectionNames, listCollectionNamesByPrefix
    caffeine:
      spec: expireAfterWrite=1m

#! Spring MongoClient
---
spring:
  data:
    mongodb:
      uri: ${mongo.uri}
      database: ${mongo.db}

#! Server
server:
  port: 8080
  servlet:
    context-path: /api

#! Security
security:
  enabled: false
#  grafana:
#    url: http://127.0.0.1/grafana/api/user

#! Mongo
mongo:
  uri: mongodb://127.0.0.1:27017
  db: sip3
  max-execution-time: 10000
  batch-size: 128

#! Application
time-suffix: yyyyMMdd
session:
  default-limit: 50
  use-x-correlation-header: true
  show-retransmits: true
  ignore-nanos: true
  call:
    max-legs: 10
    aggregation-timeout: 60000
    termination-timeout: 10000
  register:
    max-legs: 10
    aggregation-timeout: 10000
    duration-timeout: 900000
  media:
    block-count: 28
    termination-timeout: 60000

cache:
  refresh-rate: 55000

springdoc:
  swagger-ui:
    path: /swagger-ui/